# Generated by Django 4.1.3 on 2022-11-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-created_at',)},
        ),
    ]
